### ISSUE TITLE
lldb-vscode始终配置不成功

### ISSUE THREAD

**Issue by nehcuh** [xhcoding/doom-private#1]
RT，按照指定链接的方式，找不到相应的liblldb.so，还有 LLDB.framework又是什么东东，😌，能不能给一个中文的配置教程，万分感谢

**Comment by xhcoding** [comment]
LLDB.framework是MAC需要的东西，我不了解。liblldb.so在你编译的lib目录里，把它复制到lldb-vscode链接的位置，可以用`lld lldb-vscode`查看具体的位置。如下面是我的信息：
```
	liblldb.so.8svn => /home/xhcoding/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/bin/./../lib/liblldb.so.8svn (0x00007fc91ca6f000)
	
```
把`liblldb.so.8svn`放在`/home/xhcoding/.vscode/extensions/llvm-org.lldb-vscode-0.1.0/lib/`下就可以找到
