### ISSUE TITLE
注意！！！

### ISSUE THREAD

**Issue by ErnestDong** [xhcoding/doom-private#4]
你的GitHub密码留下了，建议把敏感信息新建一个custom.el，然后添加到gitignore里面

**Comment by xhcoding** [comment]
感谢指出，我已经移除了。

**Comment by ErnestDong** [comment]
> 感谢指出，我已经移除了。

还是可以回滚过去的，建议改个密码

**Comment by xhcoding** [comment]
这用来预览 markdown 的 token，在 github 上把这个 token 移除了， token就失效了。
